#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_terragrunt="$(terragrunt --version 2>/dev/null | awk '{print $3}' | perl -pe 's{^v}{}' || true)"
  jq -n \
    --arg terragrunt "$ver_terragrunt" \
    '{terragrunt: $terragrunt}'
}

version "$@"
